import { createClient } from "npm:@supabase/supabase-js@2";
import QRCode from "npm:qrcode@1.5.4";

const cors = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const esc = (s: string) =>
	s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

Deno.serve(async (req) => {
	if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

	const json = (body: unknown, status = 200) =>
		new Response(JSON.stringify(body), {
			status,
			headers: { ...cors, "Content-Type": "application/json" },
		});

	const admin = createClient(
		Deno.env.get("SUPABASE_URL")!,
		Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
	);

	// 1. Only a logged-in admin may approve
	const jwt = req.headers.get("Authorization")?.replace("Bearer ", "");
	if (!jwt) return json({ error: "Not signed in" }, 401);

	const { data: { user } } = await admin.auth.getUser(jwt);
	if (!user) return json({ error: "Not signed in" }, 401);

	const { data: adminRow } = await admin
		.from("admins")
		.select("auth_id")
		.eq("auth_id", user.id)
		.maybeSingle();
	if (!adminRow) return json({ error: "Forbidden" }, 403);

	// 2. Load the application
	const { registrationId } = await req.json();
	const { data: reg } = await admin
		.from("Registration").select("*").eq("id", registrationId).single();
	if (!reg) return json({ error: "Application not found" }, 404);
	if (reg.status === "approved") return json({ error: "Already approved" }, 409);
	if (!reg.email) return json({ error: "Applicant has no email" }, 400);

	// 3. Copy into PWDinformation (number + token are generated by the DB)
	const { data: pwd, error: insertError } = await admin
		.from("PWDinformation")
		.insert({
			firstName: reg.firstName,
			middleName: reg.middleName,
			lastName: reg.lastName,
			dateofBirth: reg.dateofBirth,
			homeAddress: reg.homeAddress,
			disabilityProfile: reg.dissabilityProfile, // spelled differently in each table
			email: reg.email,
			document_path: reg.document_path,
		})
		.select("pwdNum, qr_token")
		.single();
	if (insertError || !pwd) return json({ error: insertError?.message }, 500);

	const { error: updateError } = await admin
		.from("Registration").update({ status: "approved" }).eq("id", registrationId);
	if (updateError) return json({ error: updateError.message }, 500);

	// 4. Generate the QR (contains only the token) and email it
	let emailSent = false;
	try {
		const qrBase64 = (await QRCode.toDataURL(pwd.qr_token, { width: 400 })).split(",")[1];

		const mail = await fetch("https://api.resend.com/emails", {
			method: "POST",
			headers: {
				Authorization: `Bearer ${Deno.env.get("RESEND_API_KEY")}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				from: "MSWDO Guagua <no-reply@yourdomain.com>",
				to: [reg.email],
				subject: "Your PWD registration is confirmed",
				html: `<p>Hello ${esc(reg.firstName)},</p>
					<p>Your registration with the Guagua MSWDO has been approved.</p>
					<p>Your PWD ID number: <strong>${esc(String(pwd.pwdNum))}</strong></p>
					<p>Your QR code is attached. Log in to view your Digital PWD ID.</p>`,
				attachments: [{ filename: "pwd-qr.png", content: qrBase64 }],
			}),
		});
		emailSent = mail.ok;
		if (!mail.ok) console.error("Resend failed:", mail.status, await mail.text());
	} catch (e) {
		console.error("Email step crashed:", e);
	}

	return json({ ok: true, pwdNumber: pwd.pwdNum, emailSent });
});